# 模型量化编译配置文件

model: {
  # 【必填】模型框架, 目前仅支持onnx
  framework: onnx,

  # 【必填】编译后模型名，必须设置
  name: ,

  # 【必填】量化文件以及各种过程文件保存路径
  save_dir: ./output,

  # 【必填】模型权重路径
  weight: ,

  # 【必填】模型输入配置
  # 目前不能分别设置多个输入的NHWC->NCHW的转换, 必须相同
  inputs: [
    {
      name: input.1, # 【必填】输入名称
      shape: [1, 3, 224, 224], # 【必填】原模型输入形状
      layout: NCHW,  # 【必填】输入数据布局，支持 NCHW，NHWC
      # 【必填】训练模型的输入，Feature结尾表示非图片数据，RGB/BGR/YUV表示图片数据
      # 支持的Feature类型为Int8Feature,Uint8Feature,Int16Feature,Float16Feature,Float32Feature,Float64Feature
      # 支持的图像类型为RGB,BGR,YUV444,YUV422,YUV420
      format: RGB,
      # 【可选】如果输入为图像，可利用芯片resizer做部分前处理，依次为crop->resize->pad
      image: {
        format: YUV422, # 支持YUV422/YUV420/YUV444
        size: [224, 224], # [height, width]
        crop: [0, 0, 224, 224], # [top, left, height, width]
      },
      dtype: uint8, # 【必填】模型原始输入数据类型(预处理之前)，支持数据类型uint8, float32, int16, float16
      mean: [ 0.0, 0.0, 0.0 ],   # 【可选】输入除以255后的均值，默认为0，支持broadcast
      std: [ 1.0, 1.0, 1.0 ],   # 【可选】输入除以255后的标准差，默认为1，支持broadcast
    }
  ],

  # 模型的python处理类(定义在PYTHONPATH可搜索路径下hm_model.py中，demo/accuracy必须设置)
  impl_class: ,
}

# 【quant必填】
quant: {
  # 【可选】量化配置文件
  ptq_cfg_path: ,

  # 【必填】量化输入数据路径, 留空表示使用随机数据
  calib_dir: ,

  # 【必填】量化使用的数据数量
  calib_num: ,

  # 【必填】量化调试等级0:no response; 1:print laywise compare
  debug_level: 1,

  # 【可选】校准方法 "kl", "min_max", "percentile_0.99..", "l2norm"(暂不支持), 默认min_max
  calib_method: ,
}

# 【test必填】
test: {
  # 【可选】用于test数据比对，默认随机数
  data_path: ,
}

# 【build必填】
build: {
  # 编译优化等级, 缺省默认为0(暂不支持)
  opt_level: 0,
}

# 【demo必填】
demo: {
  # 【必填】指定demo的测试数据路径
  data_dir: ,

  # 【必填】demo测试样例数，实际测试数为数据路径内数据数与本数的较小者，配置0为数据路径内所有数据
  test_num: 20,
}

# 【perf必填】
perf: {
  # 【可选】指定性能测试使用的数据路径，不设置则使用随机数（目前仅支持使用随机数）
  data_dir: ,

  # 【必填】性能测试样例数
  test_num: 10,

  # 【必填】性能测试模式(目前仅支持throughput)，支持throughput和latency
  mode: throughput,

  # 【可选】性能测试是否包含前后处理，默认为false(暂不支持)
  end2end: ,
}

# 【eval必填】
eval: {
  # 【必填】精度测试的数据集路径
  data_dir: ,
  # 【必填】test精度测试样例数，实际测试数为数据集内数据数与本数的较小者，配置0为数据集内所有数据
  test_num: 0,

  # 【必填】数据集python处理类(定义在PYTHONPATH可搜索路径下hm_dataset.py中)
  dataset_class: ,
}

